{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "#Q1. What are the two latest user-defined exception constraints in Python 3.X?"
      ],
      "metadata": {
        "id": "MZNvQAQuMmbv"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Ans-1. **Exception subclasses:** Python allows you to define your own exception classes by subclassing the built-in Exception class or any of its subclasses. By creating a custom exception class, you can define your own exception hierarchy and handle specific types of errors in your code\n",
        "\n",
        "2. Exception handling with try-except blocks: Python provides the try-except statement to catch and handle exceptions. By using this construct, you can specify the code that may raise an exception within a try block, and define the handling logic in one or more except blocks."
      ],
      "metadata": {
        "id": "-Eucp-YgMuVv"
      }
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "nqzgUCegMNLT"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "#Q2. How are class-based exceptions that have been raised matched to handlers?"
      ],
      "metadata": {
        "id": "tsCcsRsYNDW0"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Ans- In Python, class-based exceptions that have been raised are matched to handlers based on the inheritance hierarchy of the exception classes and the order in which the except blocks are defined. When an exception is raised, Python searches for a matching except block in the current scope and its enclosing scopes.\n",
        "\n",
        "The exception handling process follows these steps:\n",
        "\n",
        "1. The try block is executed. If an exception is raised within the try block, the normal flow of execution is interrupted, and Python looks for an appropriate except block to handle the exception.\n",
        "\n",
        "2. Python starts searching for a matching except block from the innermost scope and proceeds to outer scopes until a suitable handler is found.\n",
        "\n",
        "3. Each except block specifies the exception class or classes it can handle. If the raised exception matches the specified class or a subclass of it, the corresponding except block is executed. If no matching handler is found, the exception propagates to the next enclosing try statement or, if there is none, it results in an unhandled exception error.\n",
        "\n",
        "4. It's important to note that the order of the except blocks is significant. If multiple except blocks can handle the raised exception, the first matching block encountered during the search is executed. Therefore, more specific exception classes should be placed before more general ones to ensure they are caught correctly."
      ],
      "metadata": {
        "id": "oelUPgJzNLcq"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "Oqjw0BL6NEbQ"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "#Q3. Describe two methods for attaching context information to exception artefacts."
      ],
      "metadata": {
        "id": "AResmJlnNW7q"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Ans- When dealing with exceptions in Python, it's often useful to attach additional context information to exception artifacts to provide more meaningful error messages or to aid in debugging.\n",
        "\n",
        "1. Exception Arguments:\n",
        "\n",
        "When raising an exception, you can provide additional context information by passing arguments to the exception class. These arguments can be accessed later when handling the exception to provide more details about the error.\n",
        "\n",
        "2. Exception Chaining:\n",
        "\n",
        "Exception chaining is a technique where you catch one exception, attach additional context information, and then raise a new exception while preserving the original exception as the cause. This allows you to propagate both the original exception and the additional context information."
      ],
      "metadata": {
        "id": "SysBSnxmNcXZ"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "MStQwR28NXqV"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "#Q4. Describe two methods for specifying the text of an exception object&#39;s error message."
      ],
      "metadata": {
        "id": "jJlEchfiNvYK"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Ans-When specifying the text of an exception object's error message in Python, there are several methods available.\n",
        "\n",
        "1. Using the args attribute:\n",
        "\n",
        "The args attribute of an exception object allows you to specify the error message as a tuple of arguments. By convention, the first element of the tuple is typically used to store the error message string.\n",
        "\n",
        "2. Creating a custom exception class:\n",
        "\n",
        "Python allows you to create your own custom exception classes by subclassing the built-in Exception class or any of its subclasses. By defining a custom exception class, you can specify the error message in a more structured and readable manner."
      ],
      "metadata": {
        "id": "9mWzyI6xN12D"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "warLudmaNxMk"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "#Q5. Why do you no longer use string-based exceptions?"
      ],
      "metadata": {
        "id": "t5FlZWMoODJY"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Ans- In Python, it is generally recommended to avoid using string-based exceptions. Instead, it is preferred to use class-based exceptions.\n",
        "\n",
        "1. Clarity and Readability: Class-based exceptions provide a clearer and more expressive way of handling and documenting exceptions. By using exception classes, you can define meaningful and descriptive names for specific types of errors, making it easier to understand the cause and nature of an exception.\n",
        "\n",
        "2. Inheritance and Hierarchy: Class-based exceptions allow for the creation of an exception hierarchy. You can define exception subclasses that inherit from more general exception classes, creating a structured hierarchy of exceptions. This hierarchy can be leveraged to catch and handle exceptions at different levels of granularity, improving code organization and maintainability.\n",
        "\n",
        "3. Type Checking and Debugging: With class-based exceptions, you can perform type checking on exceptions, enabling better static analysis and debugging capabilities. Tools such as static analyzers, IDEs, and linters can provide more accurate type information and suggest potential issues when you use class-based exceptions. This can help catch errors early in the development process and improve the overall reliability of your code.\n",
        "\n",
        "4. Exception Handling Granularity: Class-based exceptions allow for fine-grained exception handling. By defining specific exception classes for different error scenarios, you can catch and handle exceptions at various levels of granularity. This allows you to provide appropriate error handling logic based on the specific type of exception, improving the robustness and resilience of your code.\n",
        "\n",
        "5. Future Compatibility: Python's exception handling mechanisms have been evolving, and string-based exceptions are considered a legacy approach. While string-based exceptions are still supported in Python for backward compatibility reasons, they are no longer the recommended way of handling exceptions. As Python continues to evolve, it's important to align with the best practices and preferred patterns."
      ],
      "metadata": {
        "id": "JxETJiqLORhR"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "G6S07jZTOEKB"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}